import type {
  DraftEvent,
  RunnerSnapshot,
  StageCatalogEntry,
} from "../../src/generated/bindings";

export const stages: StageCatalogEntry[] = [
  {
    id: "smoke-stage-1",
    code: "1-1",
    name: "冒烟关卡一",
    levelPath: "smoke/one.json",
  },
  {
    id: "smoke-stage-2",
    code: "1-2",
    name: "冒烟关卡二",
    levelPath: "smoke/two.json",
  },
];

export function createSnapshot(): RunnerSnapshot {
  const deploy: DraftEvent = {
    id: "event-deploy",
    frame: 30,
    order: 0,
    kind: "deploy",
    operator: "smoke-operator",
    tile: "C5",
    direction: "right",
    label: "部署样本",
    complete: true,
    attemptId: "attempt-1",
    sourceRecordingId: null,
    sourceCandidateId: null,
    sourceSegmentIndex: null,
    sourceTimestampNs: null,
    frameRange: { start: 30, end: 30 },
    clockQuality: "trusted",
    timeConfirmation: "observed",
  };
  const axis = {
    title: "冒烟作战轴",
    stageId: "smoke-stage-1",
    events: [
      deploy,
      {
        ...deploy,
        id: "event-skill",
        frame: 90,
        order: 1,
        kind: "skill" as const,
        operator: null,
        direction: null,
        label: "技能样本",
        frameRange: { start: 90, end: 90 },
      },
    ],
  };
  const recognition = {
    status: "matched" as const,
    rawText: "1-1",
    stage: stages[0] ?? null,
    candidates: [],
    warning: null,
  };
  return {
    axis,
    session: {
      id: "session-smoke",
      currentRevisionId: "revision-active",
      activeRecordingRevisionId: "revision-active",
      armedRevisionId: null,
      revisions: [
        {
          id: "revision-old",
          sequence: 1,
          parentRevisionId: null,
          source: "takeover",
          attemptId: "attempt-1",
          createdFrame: 0,
          axis: { ...structuredClone(axis), title: "旧版本作战轴" },
          takeover: null,
          recordingMerge: null,
        },
        {
          id: "revision-active",
          sequence: 2,
          parentRevisionId: "revision-old",
          source: "recordingMerge",
          attemptId: "attempt-1",
          createdFrame: 30,
          axis: structuredClone(axis),
          takeover: null,
          recordingMerge: {
            recordingAnalysisId: "analysis-smoke",
            segmentIndex: 0,
            frameOffset: 0,
            candidateIds: [],
          },
        },
      ],
      takeover: {
        status: "idle",
        generation: 0,
        baseRevisionId: null,
        newRevisionId: null,
        requestedSourceTimestampNs: null,
        inheritedAnchor: null,
        uncertainReceiptSequences: [],
        message: null,
      },
    },
    consoleMode: "manualRecording",
    recordingAttempts: [],
    stagedRecordingEvents: [],
    settings: {
      version: 1,
      theme: "dark",
      framesPerCost: 30,
      gameUiScale: 100,
      pauseKey: "Escape",
      skillKey: "D",
      retreatKey: "A",
      bindingsConfirmed: true,
    },
    monitor: {
      sourceKind: "recording",
      connectionState: "ready",
      sourceName: "smoke-fixture.mp4",
      windowId: null,
      battleState: "notInBattle",
      confidence: 1,
      costPhase: null,
      costTotal: 0,
      costFull: false,
      trusted: true,
      error: null,
      captureWarning: null,
      lastEventSequence: null,
      lastSourceTimestampNs: null,
      droppedObservations: 0,
      recordingProgress: 100,
      recordingAnalysisId: "analysis-smoke",
      traceDurationFrames: 600,
      tracePoints: [],
      recordingSegments: [0, 1].map((index) => ({
        index,
        sourceStartFrame: index * 300,
        sourceEndFrame: (index + 1) * 300 - 1,
        gameDurationFrames: 300,
        stageRecognition: { ...recognition, stage: stages[index] ?? null },
      })),
      recordingCandidates: [],
      stageRecognition: recognition,
    },
    clock: {
      mode: "human",
      active: false,
      receivingObservations: false,
      frame: 0,
      speedFifths: 5,
      quality: "waiting",
      uncertaintyFrames: 0,
      sourceTimestampNs: null,
      anchor: null,
    },
    stageSafety: {
      status: "matched",
      expectedStageId: "smoke-stage-1",
      observedStage: stages[0] ?? null,
      source: "manual",
    },
    frame: 0,
    time: "00:00:00",
    speed: 1,
    status: "waiting",
    recording: true,
    strategy: "notify",
    proxy: {
      enabled: false,
      status: "disabled",
      message: null,
      receipts: [],
      stopReason: null,
      pauseProof: "none",
      pauseProofMessage: null,
      runId: null,
    },
    nextEvent: deploy,
    countdownFrames: 30,
    errorFrames: 0,
    lastMessage: null,
    notices: [],
    alwaysOnTop: true,
    clearPending: false,
  };
}
